config/routes.rb
EtsyRenewAgent::Application.routes.draw do

  resources :access_tokens, :only => [:edit, :update]
  resources :users, :only => [:new, :create]
  resource :session, :only => [:new, :create, :destroy]

  get "etsy/authorize"
  get "etsy/new_authorization"

  root :to => "welcome#index"
end

app/models/access_token.rb
class AccessToken < ActiveRecord::Base
  attr_accessible :secret,
    :token,
    :user,
    :shop_name,
    :enable_auto_renew,
    :renew_every_x_minutes


  belongs_to :user


  validates_presence_of :user,
    :secret,
    :token,
    :shop_name

  validates_numericality_of :renew_every_x_minutes,
    :only_integer => true,
    :greater_than_or_equal_to => 10

  validates_inclusion_of :enable_auto_renew,
    :in => [ true, false ]
end

app/models/request_token.rb
class RequestToken < ActiveRecord::Base
  attr_accessible :secret,
    :token,
    :user


  belongs_to :user


  validates_presence_of :user,
    :secret,
    :token
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!

  attr_accessible :email,
    :password,
    :password_confirmation


  has_many :request_tokens
  has_many :access_tokens


  validates_presence_of :email
  validates_uniqueness_of :email

  validates_presence_of :password, :on => :create
  validates_confirmation_of :password, :if => :password
end

app/controllers/access_tokens_controller.rb
class AccessTokensController < ApplicationController
  before_filter :load_access_token

  def edit
  end

  def update
    @access_token.update_attributes params[:access_token]

    if @access_token.save
      redirect_to root_path, :notice => "Shop Settings Updated!"
    else
      render :edit
    end
  end

  def load_access_token
    @access_token = AccessToken.find params[:id]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :require_login
end

app/controllers/etsy_controller.rb
class EtsyController < ApplicationController

  def new_authorization
    e_request = Etsy.request_token
    RequestToken.create! :token => e_request.token,
      :secret => e_request.secret,
      :user => current_user
    redirect_to Etsy.verification_url
  end

  def authorize
    linked_request = RequestToken.find_by_token params[:oauth_token]

    if linked_request
      e_access = Etsy.access_token(
        linked_request.token,
        linked_request.secret,
        params[:oauth_verifier]
      )

      e_user = Etsy.myself( e_access.token, e_access.secret )

      AccessToken.create! :token => e_access.token,
        :secret => e_access.secret,
        :user => current_user,
        :shop_name => e_user.shop.name

      linked_request.destroy

      notice = 'Account linked'
    else
      notice = 'Unable to locate request token'
    end

    redirect_to root_path, :notice => notice
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :require_login

  def new
  end

  def create
    if login params[:email], params[:password]
      redirect_to root_path, :notice => "You are now logged in!"
    else
      flash[:error] = "Invalid email address or password."
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_path, :notice => "You have been logged out."
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, :only => [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new params[:user]

    if @user.save
      auto_login(@user)
      redirect_to root_path
    else
      render :new
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @request_tokens = current_user.request_tokens

    @access_tokens = current_user.access_tokens
  end
end

app/helpers/access_tokens_helper.rb
module AccessTokensHelper
  def every_x_minute_options
    [ 10, 15, 20, 30, 60, 120, 240, 720 ]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/access_tokens/edit.html.haml
%h1
  Managing Shop :: 
  = @access_token.shop_name

= twitter_bootstrap_form_for @access_token do |f|
  = f.label 'Enable Auto Renew:' do |inline_f|
    = inline_f.radio_button :enable_auto_renew, true, "Yes please, auto renew my listings"
    = inline_f.radio_button :enable_auto_renew, false, "Nope, I'll manage things myself"

  = f.select :renew_every_x_minutes, 'Renew A Listing Every X Minutes:', every_x_minute_options, :class => 'span1'

  .form-actions
    = f.submit 'Update Settings', :class => 'btn btn-medium btn-primary'
    = link_to 'Back', root_path, :class => 'btn btn-medium'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "EtsyRenewAgent"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'Etsy Renew Finder', root_path, :class => 'brand'
          .container.nav-collapse
            %ul.nav
              - if logged_in?
                %li= link_to "Logout", session_path, :method => :delete
              - else
                %li= link_to "Login", new_session_path

    .container

      .row
        .span12
          = bootstrap_flash
          = yield

      %footer
        %p &copy; Etsy Renew Finder 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/layouts/fixed.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "EtsyRenewAgent"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") EtsyRenewAgent
          .container.nav-collapse
            %ul.nav
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"

    .container

      .row
        .span9
          = bootstrap_flash
          = yield
        .span3
          .well.sidebar-nav
            %h3 Sidebar
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Link 1", "/path1"
              %li= link_to "Link 2", "/path2"
              %li= link_to "Link 3", "/path3"
    
      %footer
        %p &copy; Company 2012
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/users/new.html.haml
%h1 Create Your Account

= twitter_bootstrap_form_for @user do |f|
  = f.text_field :email
  = f.password_field :password
  = f.password_field :password_confirmation
  = f.submit "Create"

app/views/welcome/index.html.haml
%h2 My Linked Shops

%p.well
  Link up your Etsy shops, and we'll renew your oldest items for you.
  Get more results for your existing inventory!

- if @access_tokens.any?
  %table.table.table-striped
    %thead
      %tr
        %th Shop Name
        %th Linked On
        %th Listing Auto Renew Enabled
        %th &nbsp;
    %tbody
      - @access_tokens.each do |token|
        %tr
          %td= token.shop_name
          %td= token.created_at
          %td= token.enable_auto_renew ? "Yep, every #{token.renew_every_x_minutes} minutes" : 'Nope'
          %td
            = link_to 'Manage Renew Settings', edit_access_token_path(token), :class => 'btn btn-small'
- else
  %p None yet, get started!

.form-actions
  = link_to 'Link New Shop', etsy_new_authorization_path, :class => 'btn btn-medium btn-success'